### PR TITLE
Added example for Yahoo Mail service

### PR DESCRIPTION
**Pull request by prabackar**

### CODE REVIEW

**Comment by Synchro** [comment]
Sorry, but there really isn't sufficient value in this. Nobody should be advocating using port 465 which is is obsolete and deprecated. Yahoo supports tls on port 587, so its settings are identical to gmail other than the host name, so it's not worth adding all this for that one tiny difference. Also PRs should be made against the upstream repo - this is my personal fork.

**Comment by wojsmol** [comment]
Welcome
> Also PRs should be made against the upstream repo - this is my personal fork.
IMHO the problem with sending PRs to this repo instead of https://github.com/PHPMailer/PHPMailer may partly result from the fact that a link to this repo is placed on http://phpmailer.worxware.com/.
Regards

**Comment by Synchro** [comment]
I know - I've asked for it to be changed several times.

**Comment by prabackar** [comment]
Thank you for your explanation about the PORT differences. I tested on 587 with tls, which works as you have mentioned.

**Pull request closed without merging**
